### ISSUE TITLE
Removal of XML parser?

### ISSUE THREAD

**Issue by vonj** [anthonyharrison/lib4sbom#1]
I was surprised to see the XML parser being removed , can it be put back?

**Comment by anthonyharrison** [comment]
@vonj It was removed becuase it was incomplete but It can be added at a future release. I primarily see JSON format for CycloneDX SBOMs with most users saying that JSON is much less problematic than XML. Note that the XML format for SPDX is still experimental with no officially released schema.

**Comment by rhaley-starfish** [comment]
I would also be happy to see a feature to generate CycloneDX files in XML.

**Comment by anthonyharrison** [comment]
> I would also be happy to see a feature to generate CycloneDX files in XML.

@rhaley-starfish It is on my todo list - it just hasn't made it to the top yet! However I don't see as much demand for CycloneDX XML documents as much as JSON formatted documents which is why the library has currently focused on JSON rather than XML.
