### ISSUE TITLE
Own id is not saved. An id is always generated.

### ISSUE THREAD

**Issue by michanc** [anthonyharrison/lib4sbom#25]
An id was set with the function set_id (SBOMPackage). However, a generated id is written when saving.

In my opinion, the problem can be found in the _validate_id function (File generator.py). len(re.findall(r"([0-9a-zA-Z\.\-\+]+)$", id)) == len(id) is not correct here.

**Comment by anthonyharrison** [comment]
@michanc The _validate_id is supposed to be validating that the id is valid according to the SPDX standard which only allows numbers, letters and a few extra characters e.g. . and -. 

What id are you providing?

**Comment by michanc** [comment]
I would currently like to use the combination of name and version (boost-1.72.0). In my opinion, the function for the check is not implemented correctly. The function re.findall returns a list of matches. In this case the length 1 should always be correct for a valid id.
