### ISSUE TITLE
feat: Include provided locations in cyclonedx sbom report utilizing evidence key.

### ISSUE THREAD

**Issue by Mayankrai449** [anthonyharrison/lib4sbom#31]
The cycloneDX report needs to be enriched with the file location where the products are found. This should follow the cycloneDX format which utilizes Evidence field with Occurrences to show locations. 

![Screenshot 2024-03-06 210620](https://github.com/anthonyharrison/lib4sbom/assets/110732414/72e0192b-dd59-4a2c-87e0-e5b12f847ce4)

The locations of products would be provided in
https://github.com/intel/cve-bin-tool/blob/3f15be82b8cd87108642b2c2a9fa800b88e479be/cve_bin_tool/output_engine/__init__.py#L906

and the lib4sbom is expected to handle this and include locations in report 
![Screenshot 2024-03-20 223441](https://github.com/anthonyharrison/lib4sbom/assets/110732414/3cc900f3-a7db-4f0d-9ba9-af804bb4aa5e)

**Comment by anthonyharrison** [comment]
See [commit](https://github.com/anthonyharrison/lib4sbom/commit/bceff4aa75ded3baf0d67e93763da655a04d13bf)
