### ISSUE TITLE
Packages with same name Ignored in the scan of SPDX file

### ISSUE THREAD

**Issue by mastersans** [anthonyharrison/lib4sbom#33]
For reference do checkout this.
Related: [cve-bin-tool issue  4058](https://github.com/intel/cve-bin-tool/issues/4058)

while scanning a spdx sbom file in json format containing two different version packages of openssl the tools is outputing only 1 package whereas is should display both, only first occurence of the package is displayed, on investigation it is found that it is due to this particular if statement:
https://github.com/anthonyharrison/lib4sbom/blob/0dae9bbba17bba8149706ec7daafb3c0e4322623/lib4sbom/spdx/spdx_parser.py#L433

below is a output of a print statement showing contents of packages dictionary where is can be seen only one package is taken into account:
```
{
    "openssl": {
        "name": "openssl",
        "type": "LIBRARY",
        "version": "1.1.1f",
        "id": "openssl_1.1.1f",
        "supplier_type": "Organization",
        "supplier": "OpenSSL",
        "originator_type": "Organization",
        "originator": "OpenSSL",
        "homepage": "http://www.openssl.org/",
        "licenseconcluded": "LicenseRef-OpenSSL",
        "licensedeclared": "LicenseRef-OpenSSL",
        "downloadlocation": "http://www.openssl.org/source/",
        "description": "OpenSSL library version 1.1.1f",
    }
}
```

**Comment by anthonyharrison** [comment]
@mastersans  Yes

The following approach might be appropriate without the check for the existence of the package name already in the list of packages.

```python
            package_tuple = (package, version)
            packages[package_tuple] = spdx_package.get_package()
```
