### ISSUE TITLE
Incorrect detection of package license

### ISSUE THREAD

**Issue by EvaSDK** [anthonyharrison/lib4sbom#49]
Hello,

I was doing some tests on internal project and came across a strange problem.
I'm using click and jinja2 in a project and click is getting the license correctly identified as BSD-3-Clause while jinja is getting NOASSERTION. Looking into the other packages, it appears markupsafe, from pallets as well, is getting BSD-3-Clause correctly identified.

I clone the respective projects at the release version I'm using and both run the same declarations for their license. The only difference I found is the year. I may or may not have time to submit a PR but I wanted to share the issue right away.

**Comment by EvaSDK** [comment]
```
PackageName: click
SPDXID: SPDXRef-Package-2-click
PackageVersion: 8.1.7
PrimaryPackagePurpose: LIBRARY
PackageSupplier: NOASSERTION
PackageDownloadLocation: https://pypi.org/project/click/8.1.7
FilesAnalyzed: false
PackageChecksum: SHA1: 874ca2bc1c30d93a4ac6e36a15ed685eafe89097
PackageLicenseDeclared: BSD-3-Clause
PackageLicenseConcluded: BSD-3-Clause
PackageCopyrightText: NOASSERTION
PackageSummary: <text>Composable command line interface toolkit</text>
ExternalRef: PACKAGE_MANAGER purl pkg:pypi/click@8.1.7
#####

PackageName: jinja2
SPDXID: SPDXRef-Package-4-jinja2
PackageVersion: 3.1.4
PrimaryPackagePurpose: LIBRARY
PackageSupplier: NOASSERTION
PackageDownloadLocation: https://pypi.org/project/jinja2/3.1.4
FilesAnalyzed: false
PackageLicenseDeclared: NOASSERTION
PackageLicenseConcluded: NOASSERTION
PackageCopyrightText: NOASSERTION
PackageSummary: <text>A very fast and expressive template engine.</text>
ExternalRef: PACKAGE_MANAGER purl pkg:pypi/jinja2@3.1.4
#####

PackageName: markupsafe
SPDXID: SPDXRef-Package-5-markupsafe
PackageVersion: 2.1.5
PrimaryPackagePurpose: LIBRARY
PackageSupplier: NOASSERTION
PackageDownloadLocation: https://pypi.org/project/markupsafe/2.1.5
FilesAnalyzed: false
PackageChecksum: SHA1: fbba4acd0312826cec9cfe18371c7df07962cb65
PackageLicenseDeclared: BSD-3-Clause
PackageLicenseConcluded: BSD-3-Clause
PackageCopyrightText: NOASSERTION
PackageSummary: <text>Safely add untrusted strings to HTML/XML markup.</text>
ExternalRef: PACKAGE_MANAGER purl pkg:pypi/markupsafe@2.1.5
#####
```

**Comment by EvaSDK** [comment]
Nevermind, after digging a bit more, jinja2 3.1.4 is using pyproject.toml to define license via setuptools pyproject `license = {file = "LICENSE.txt"}` which would require parsing while markupsafe 2.1.5 is using the legacy setuptools setup.cfg `license = BSD-3-Clause`. Same for click 8.1.7. However, latest main branch shows all moved to pyproject.toml only.

The packages do provide license classifier as well, maybe it would be a good idea to use it as a fallback before eventually parsing the text file. Iirc classifiers should easily map to SPDX identifiers. See https://pypi.org/classifiers/.

**Comment by anthonyharrison** [comment]
@EvaSDK - I assume you are using sbom4python to generate the SBOM. The licence information is extracted from the metadata when the package is installed.; however the latest version of sbom4python (0.11.1) does  consider alternative sources of licence information as well.

**Comment by anthonyharrison** [comment]
To be handled by https://github.com/anthonyharrison/sbom4python/issues/18
