### ISSUE TITLE
ModuleNotFoundError: No module named 'lib4sbom.data.service'

### ISSUE THREAD

**Issue by nedsouza** [anthonyharrison/lib4sbom#53]
Hi Anthony,

I ran the lib4sbom/examples/summary.py file and I get the following error :

desktop:~/sbom$ python3 summary.py
Traceback (most recent call last):
  File "summary.py", line 11, in <module>
    from lib4sbom.data.service import SBOMService
ModuleNotFoundError: No module named 'lib4sbom.data.service'

**Comment by anthonyharrison** [comment]
What version of lib4sbom are you using?

**Comment by nedsouza** [comment]
Can you please share the command to get the version for lib4sbom -

**Comment by anthonyharrison** [comment]
> Can you please share the command to get the version for lib4sbom -

The quickest way is

`pip list | grep lib4sbom`

If you don't have the latest version (0.7.5), `pip install lib4sbom --upgrade`

**Comment by nedsouza** [comment]
I was on lib4sbom 0.4.3. I upgraded to 0.7.5 and it works.
