### ISSUE TITLE
Components with same name but different bom-ref

### ISSUE THREAD

**Issue by howellx** [anthonyharrison/lib4sbom#54]
Hi there,

I noticed that if there are 2 components in the SBOM with the same name and version, the SBOM-parser only creates one dict for the second package and the first one doesn't show up. I'm not sure if this was intentional behavior or not but thought I'd bring it up here.  

The reason I would need these to be different packages is because they have different dependencies. It is odd that they have the exact same properties, so perhaps this is more an issue with my SBOM generation method, but to handle this edge-case after the fact, it would still be useful for both packages to be present in the parser (at least for me, again I'm not sure if this was intentional behavior or not). 

I've attached my SBOM, and the packages of interest are `pkg:maven/org.pitest/pitest-maven@dev-SNAPSHOT?type=maven-plugin` and `pkg:maven/org.pitest/pitest-maven@dev-SNAPSHOT?type=jar`. Only `pkg:maven/org.pitest/pitest-maven@dev-SNAPSHOT?type=jar` gets a dict created for it in `sbom_packages` when I run:

`sbom_parser = SBOMParser()`
`sbom_parser.parse_file("../json sboms/pitest_bom_modified.json") `
`sbom = sbom_parser.get_sbom()`
`sbom_packages = sbom_parser.get_packages()`

[pitest_bom.json](https://github.com/user-attachments/files/17389021/pitest_bom.json)

**Comment by anthonyharrison** [comment]
@howellx Multiple versions of the same package are handled. The package name and version are used and not the bom-ref. In your example the only difference is in the bom-ref (a different type plugin or jar) as the name and version are the same. In the case of a clash, the latest version of the package will be retained when parsing the SBOM.

The approach chosen is for consistency between SPDX and CycloneDX SBOMs. One way to resolve your example would be to use the PURL identifier (which in your example is also the bom-ref) but the majority of SBOMs do not specify a purl for the component. 

As a workaround, ff you use the PURL identifier as the package name, the parser should then retain both packages.

I will consider enhancing the differentiation of packages as a future enhancement

**Comment by howellx** [comment]
Okay that makes sense, thank you for the clarification

**Comment by anthonyharrison** [comment]
Updated README to explain that multiple instances of a component with the same name and version are not preserved.
