### ISSUE TITLE
Please re-raise Exceptions or raise a own exception during parsing

### ISSUE THREAD

**Issue by jloehel** [anthonyharrison/lib4sbom#59]
It's quiet confusing if `parse_file`  do not complain if there is a ValueError or a KeyError. I just a get an empty doc. It would be nice to catch the full trace with an exception to actually see what is failing. If you still want the debugging message you can catch them but please re-raise the exception or raise a own exception like `ParsingError` and describe there in detail what failed.
... or at least returning the errors.

https://github.com/anthonyharrison/lib4sbom/blob/79018441a95eef6a511f4756c8372a43a9b3f8db/lib4sbom/parser.py#L120-L125

Like that, I had to change the code (just adding `... as err:`) and set there a breakpoint to see what was going on. I would also suggest to use a logger or print on stderr instead of stdout.

**Comment by anthonyharrison** [comment]
Thanks for the suggestion @jloehel  I have tried to be as flexible and tolerant as possible with the parsing but you are right, a lib4sbom defined exception would be a better solution.

**Comment by jloehel** [comment]
@anthonyharrison Maybe one suggestion more. I would raise it like `raise SBOMParserException(f"Unable to process file {sbom_file}") from e` , to understand the root cause of the failure.

How I would use your lib:
~~~python
from lib4sbom.cyclonedx.cyclonedx_parser import CycloneDXParser
from lib4sbom.exception import SBOMParserException

from loguru import logger

parser = CycloneDXParser()
try:
    parser.parse("empty.json")
except SBOMParserException as err:
    logger.opt(exception=err).debug("Traceback for SBOM parsing error")
    logger.error(f"{err}: {err.__cause__}")
~~~

current output:
~~~
2024-12-09 14:49:33.261 | ERROR    | __main__:<module>:10 - : None
~~~

maybe better:
~~~
2024-12-09 14:50:16.092 | ERROR    | __main__:<module>:10 - Unable to process file empty.json: Expecting value: line 1 column 1 (char 0)
~~~

Of course with implicit chaining the message would be also available in __context__. But it's more clear in my opinion.
